### ISSUE TITLE
github actions is the way to go with snapshot binaries

### ISSUE THREAD

**Issue by rusefillc** [malcom2073/emstudio#6]
I am totally not pointing any body parts at David @chuckwagoncomputing but he knows github actions

**Comment by malcom2073** [comment]
I've heard good things about github actions, but I've never used them. Once there is a working prototype, I'll start digging into how to have CI/CD up and running and deploying to github for sure

**Comment by malcom2073** [comment]
First build! https://github.com/malcom2073/emstudio/releases/tag/nightly-tag-20220701025218

**Comment by malcom2073** [comment]
FWIW: I wouldn't use this build on any tune/config you care about. It's not well tested to ensure it doesn't corrupt data

**Comment by karniv00l** [comment]
@malcom2073 will you support mac? I could help with the GH actions

**Comment by malcom2073** [comment]
Closing this as complete since we now have a github actions build running automatically. I've created two new issues, #8 and #9 for tracking linux and OSX builds.
